logging:
  level:
    org.apache.tomcat.util.net.NioEndpoint: OFF
    root: trace

spring:
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            client-name: Sign in with Google
          github:
            provider: github
            client-id: ${GITHUB_CLIENT_ID:github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:github-client-secret}
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    user: sa
    password:
    url: jdbc:h2:mem:testdb
    default-schema: public
    contexts: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

totp:
  secret:
    length: 32
  code:
    length: 6
  time:
    period: 30
    discrepancy: 2
